#!/bin/bash
set -e

cd ${OPENSHIFT_TMP_DIR}
curl -s https://www.python.org/ftp/python/3.5.1/Python-3.5.1.tar.xz | tar -Jx
cd Python-3.5.1
echo "now start building Python 3.5.1..."
./configure --prefix="${OPENSHIFT_HOMEDIR}/Python" --quiet
make -j 10 --quiet > /dev/null 2>&1
make install > /dev/null 2>&1
