#!/bin/bash
set -e

forever_echo() {
    # for keeping the tcp connection, I could not mute all output
    while :
    do
        echo -n .
        sleep 1
    done
}

build_py3k() {
    INSTALL_DIR="${OPENSHIFT_HOMEDIR}/app-root/runtime/Python"
    cd ${OPENSHIFT_TMP_DIR}
    [[ -d ${INSTALL_DIR} ]] || mkdir ${INSTALL_DIR}

    curl -s https://www.python.org/ftp/python/3.5.1/Python-3.5.1.tar.xz | tar -Jx
    cd Python-3.5.1
    echo -n "now start building Python 3.5.1..."
    forever_echo &
    ./configure --prefix="${INSTALL_DIR}" --quiet
    make -j 10 --quiet > /dev/null 2>&1
    make install > /dev/null 2>&1
    echo "Python 3.5.1 installed"
}

main() {
    export PATH="${OPENSHIFT_HOMEDIR}/app-root/runtime/Python/bin/:${PATH}"
    if ! python3 --version > /dev/null; then
        build_py3k
    fi
}

main
