#!/bin/bash
set -e

export PATH="${OPENSHIFT_HOMEDIR}/Python/bin/:${PATH}"
echo "installing pip..."
curl https://bootstrap.pypa.io/get-pip.py | python3 -

pip install -r "${OPENSHIFT_REPO_DIR}/requirements.txt"
